remote_theme: pmarsceill/just-the-docs
title: WVD APAC Partner Portal
description: Your curated catalog of the latest Windows Virtual Desktop resources
logo: "/images/wvdlogo.jpg"
search_enabled: false
color_scheme: custom
heading_anchors: true
gh_edit_link: false
footer_content: "Brought to you by the Microsoft APAC OCP Tech team."