remote_theme: pmarsceill/just-the-docs
title: wvdapac.github.io
description: Your curated catalog of the latest Windows Virtual Desktop resources
search_enabled: true
color_scheme: custom
heading_anchors: true
gh_edit_link: false
footer_content: "Brought to you by the Microsoft APAC OCP Tech team."
